name: godeye_parser
description: A program that's find forrect phones by region 
publish_to: 'https://github.com/evendelger/godeye_parser'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0-213.0.dev <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.4
  dropdown_search: ^5.0.6
  file_picker: ^6.0.0
  html: ^0.15.4
  intl: ^0.18.1
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  window_manager: ^0.3.7
  sqflite: ^2.3.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  sqflite_common_ffi: ^2.3.0+2
  path_provider: ^2.1.1
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/data.csv